// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjP-ChDjvn1t1Y_QSCtU9QKAhRuBLbdsg',
    appId: '1:472150912874:web:53daf64d8a7f38491f7f13',
    messagingSenderId: '472150912874',
    projectId: 'tiktokclone-bae1b',
    authDomain: 'tiktokclone-bae1b.firebaseapp.com',
    storageBucket: 'tiktokclone-bae1b.firebasestorage.app',
    measurementId: 'G-04VKKD3GS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3bIyhKpGaZaz1UwgMDNxC4lG-j8654us',
    appId: '1:472150912874:android:08b0dd75cdfa8ff81f7f13',
    messagingSenderId: '472150912874',
    projectId: 'tiktokclone-bae1b',
    storageBucket: 'tiktokclone-bae1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt_9SB4kTDDvAr-wTQv0YdAgfNlCEyPIM',
    appId: '1:472150912874:ios:cd3d309ef91e20ee1f7f13',
    messagingSenderId: '472150912874',
    projectId: 'tiktokclone-bae1b',
    storageBucket: 'tiktokclone-bae1b.firebasestorage.app',
    iosBundleId: 'com.example.tiktokFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt_9SB4kTDDvAr-wTQv0YdAgfNlCEyPIM',
    appId: '1:472150912874:ios:cd3d309ef91e20ee1f7f13',
    messagingSenderId: '472150912874',
    projectId: 'tiktokclone-bae1b',
    storageBucket: 'tiktokclone-bae1b.firebasestorage.app',
    iosBundleId: 'com.example.tiktokFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjP-ChDjvn1t1Y_QSCtU9QKAhRuBLbdsg',
    appId: '1:472150912874:web:9b12a0e8e02ce2061f7f13',
    messagingSenderId: '472150912874',
    projectId: 'tiktokclone-bae1b',
    authDomain: 'tiktokclone-bae1b.firebaseapp.com',
    storageBucket: 'tiktokclone-bae1b.firebasestorage.app',
    measurementId: 'G-RFZEB4K8RX',
  );
}
