name: tiktok_backend
description: A backend server for the TikTok clone project.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  mongo_dart: ^0.9.4 # Hoặc 0.10.0 nếu bạn đã đổi và nó hoạt động
  crypto: ^3.0.3
  path: ^1.9.0
  shelf_multipart: ^2.0.1 # Đảm bảo bạn đang dùng phiên bản 2.x.x
  shelf_static: ^1.1.2 
  dart_dev: ^4.0.0
  shelf_cors_headers: ^0.1.5

 
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9